dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('jif.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('avatar/', include('avatar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jif/urls.py
from django.urls import path

from jif.views.index_views import IndexView

from jif.views.instituto_views import (
    InstitutoView,
    InstitutoCreateView,
    InstitutoDetailView,
    InstitutoUpdateView,
    InstitutoDeleteView
)

from jif.views.campus_views import (
    CampusView,
    CampusCreateView,
    CampusDetailView,
    CampusUpdateView,
    CampusDeleteView
)

from jif.views.edicao_views import (
    EdicaoView,
    EdicaoCreateView,
    EdicaoDetailView,
    EdicaoUpdateView,
    EdicaoDeleteView,
    EdicaoEtapaCreateView,
    EdicaoEtapaUpdateView,
    EdicaoEtapaDeleteView,
    EdicaoCategoriaCreateView,
    EdicaoCategoriaUpdateView,
    EdicaoCategoriaDeleteView,
    EdicaoModalidadeCreateView,
    EdicaoModalidadeUpdateView,
    EdicaoModalidadeDeleteView,
    EdicaoModalidadeProvaCreateView,
    EdicaoModalidadeProvaUpdateView,
    EdicaoModalidadeProvaDeleteView
)

from jif.views.categoria_views import (
    CategoriaView,
    CategoriaCreateView,
    CategoriaDetailView,
    CategoriaUpdateView,
    CategoriaDeleteView
)

from jif.views.prova_views import (
    ProvaView,
    ProvaCreateView,
    ProvaDetailView,
    ProvaUpdateView,
    ProvaDeleteView
)

from jif.views.etapa_views import (
    EtapaView,
    EtapaCreateView,
    EtapaDetailView,
    EtapaUpdateView,
    EtapaDeleteView
)

from jif.views.modalidade_views import (
    ModalidadeView,
    ModalidadeCreateView,
    ModalidadeDetailView,
    ModalidadeUpdateView,
    ModalidadeDeleteView
)

from jif.views.atleta_views import (
    AtletaView,
    AtletaCreateView,
    AtletaDetailView,
    AtletaUpdateView,
    AtletaDeleteView
)

from jif.views.inscricao_views import (
    InscricaoView,
    InscricaoCreateView,
    InscricaoDetailView,
    InscricaoUpdateView,
    InscricaoDeleteView
)

from jif.views.grafico_views import (
    GraficoView,
    InscricaoCampusJSONView,
    InscricaoModalidadeJSONView,
    InscricaoModalidadeLineJSONView
)

from .views import relatorio_views

from jif.views.usuario_views import UsuarioView


urlpatterns = [
    # Index URL
    path('', IndexView.as_view(), name='index'),
    # Instituto URLs
    path('instituto/', InstitutoView.as_view(), name='instituto'),
    path('instituto_create/', InstitutoCreateView.as_view()),
    path('instituto/<pk>/', InstitutoDetailView.as_view()),
    path('instituto/<pk>/update', InstitutoUpdateView.as_view()),
    path('instituto/<pk>/delete/', InstitutoDeleteView.as_view()),
    # Campus URLs
    path('campus/', CampusView.as_view(), name='campus'),
    path('campus_create/', CampusCreateView.as_view()),
    path('campus/<pk>/', CampusDetailView.as_view()),
    path('campus/<pk>/update', CampusUpdateView.as_view()),
    path('campus/<pk>/delete/', CampusDeleteView.as_view()),
    # Edicao URLs
    path('edicao/', EdicaoView.as_view(), name='edicao'),
    path('edicao_create/', EdicaoCreateView.as_view()),
    path('edicao/<pk>/', EdicaoDetailView.as_view()),
    path('edicao/<pk>/update', EdicaoUpdateView.as_view()),
    path('edicao/<pk>/delete/', EdicaoDeleteView.as_view()),
    path('edicao/etapa/create/<pk>/', EdicaoEtapaCreateView.as_view()),
    path('edicao/etapa/<pk>/update', EdicaoEtapaUpdateView.as_view()),
    path('edicao/etapa/<pk>/delete/', EdicaoEtapaDeleteView.as_view()),
    path('edicao/categoria/create/<pk>/', EdicaoCategoriaCreateView.as_view()),
    path('edicao/categoria/<pk>/update', EdicaoCategoriaUpdateView.as_view()),
    path('edicao/categoria/<pk>/delete/', EdicaoCategoriaDeleteView.as_view()),
    path('edicao/modalidade/create/<pk>/', EdicaoModalidadeCreateView.as_view()),
    path('edicao/modalidade/<pk>/update', EdicaoModalidadeUpdateView.as_view()),
    path('edicao/modalidade/<pk>/delete/', EdicaoModalidadeDeleteView.as_view()),
    path('edicao/prova/create/<pk>/', EdicaoModalidadeProvaCreateView.as_view()),
    path('edicao/prova/<pk>/update', EdicaoModalidadeProvaUpdateView.as_view()),
    path('edicao/prova/<pk>/delete', EdicaoModalidadeProvaDeleteView.as_view()),
    # Categoria URLs
    path('categoria/', CategoriaView.as_view(), name='categoria'),
    path('categoria_create/', CategoriaCreateView.as_view()),
    path('categoria/<pk>/', CategoriaDetailView.as_view()),
    path('categoria/<pk>/update', CategoriaUpdateView.as_view()),
    path('categoria/<pk>/delete/', CategoriaDeleteView.as_view()),
    # Prova URLs
    path('prova/', ProvaView.as_view(), name='prova'),
    path('prova_create/', ProvaCreateView.as_view()),
    path('prova/<pk>/', ProvaDetailView.as_view()),
    path('prova/<pk>/update', ProvaUpdateView.as_view()),
    path('prova/<pk>/delete/', ProvaDeleteView.as_view()),
    # Etapa URLs
    path('etapa/', EtapaView.as_view(), name='etapa'),
    path('etapa_create/', EtapaCreateView.as_view()),
    path('etapa/<pk>/', EtapaDetailView.as_view()),
    path('etapa/<pk>/update', EtapaUpdateView.as_view()),
    path('etapa/<pk>/delete/', EtapaDeleteView.as_view()),
    # Modalidade URLs
    path('modalidade/', ModalidadeView.as_view(), name='modalidade'),
    path('modalidade_create/', ModalidadeCreateView.as_view()),
    path('modalidade/<pk>/', ModalidadeDetailView.as_view()),
    path('modalidade/<pk>/update', ModalidadeUpdateView.as_view()),
    path('modalidade/<pk>/delete/', ModalidadeDeleteView.as_view()),
    # Atleta URLs
    path('atleta/', AtletaView.as_view(), name='atleta_list'),
    path('atleta_create/', AtletaCreateView.as_view()),
    path('atleta/<pk>/', AtletaDetailView.as_view()),
    path('atleta/<pk>/update', AtletaUpdateView.as_view()),
    path('atleta/<pk>/delete/', AtletaDeleteView.as_view()),
    # Inscrição URLs
    path('inscricao/', InscricaoView.as_view(), name='inscricao'),
    path('inscricao_create/', InscricaoCreateView.as_view()),
    path('inscricao/<pk>/', InscricaoDetailView.as_view()),
    path('inscricao/<pk>/update', InscricaoUpdateView.as_view()),
    path('inscricao/<pk>/delete/', InscricaoDeleteView.as_view()),
    # Relatório URLs
    path('atletacampus/', relatorio_views.atleta_campus, name='atleta_campus'),
    path('atletamodalidade/', relatorio_views.atleta_modalidade, name='atleta_modalidade'),
    path('atletaprova/', relatorio_views.atleta_prova, name='atleta_prova'),
    path('inscricoesatletas/', relatorio_views.inscricoes_atletas, name='inscricoes_atletas'),
    path('fichainscricao/<int:edicao_id>/<int:campus_id>', relatorio_views.fichaisncricao, name='ficha_inscricao'),
    # Gráfico URLs
    path('grafico/', GraficoView.as_view(), name='grafico'),
    path('dadosinscricaocampus/', InscricaoCampusJSONView.as_view(), name='dados_inscricao_campus'),
    path('dadosinscricaomodalidade/', InscricaoModalidadeJSONView.as_view(), name='dados_inscricao_modalidade'),
    path('dadosinscricaomodalidadeLine/', InscricaoModalidadeLineJSONView.as_view(), name='dados_inscricao_modalidadeLine'),
    # Usuário URL
    path('usuario/', UsuarioView.as_view(), name='usuario'),
]

jif/models.py
from django.db import models
from stdimage.models import StdImageField


class Base(models.Model):
    data_hora_cadastro = models.DateTimeField('Data do Cadastro', auto_now_add=True)
    data_hora_ultima_alteracao = models.DateTimeField('Data da Última Alteração', auto_now=True)
    ativo = models.BooleanField('Ativo', default=True)

    class Meta:
        abstract = True


class Instituto(Base):
    nome = models.CharField(max_length=100, unique=True)
    sigla = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name = 'Instituto'
        verbose_name_plural = 'Institutos'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Campus(Base):
    nome = models.CharField(max_length=100)
    instituto = models.ForeignKey(Instituto, on_delete=models.CASCADE, verbose_name='Instituto')

    class Meta:
        unique_together = ['nome', 'instituto']
        verbose_name = 'Campus'
        verbose_name_plural = 'Campi'

    def __str__(self):
        return f"{self.nome} ({self.instituto.sigla})"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Edicao(Base):
    nome = models.CharField(max_length=100, unique=True)
    data_inicio_edicao = models.DateField('Data do Início da Edição', blank=False, null=False)
    data_termino_edicao = models.DateField('Data do Término da Edição', blank=False, null=False)

    class Meta:
        verbose_name = 'Edição'
        verbose_name_plural = 'Edições'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Etapa(Base):
    edicao = models.ForeignKey(Edicao, on_delete=models.CASCADE, verbose_name='Edição')
    nome = models.CharField(max_length=100, unique=True)
    data_inicio_etapa = models.DateField('Data do Início da Etapa', blank=False, null=False)
    data_termino_etapa = models.DateField('Data do Término da Etapa', blank=False, null=False)
    data_inicio_inscricao = models.DateField('Data do Início das Inscrições', blank=False, null=False)
    data_termino_inscricao = models.DateField('Data do Término das Inscrições', blank=False, null=False)
    campi = models.ManyToManyField(Campus)

    class Meta:
        verbose_name = 'Etapa'
        verbose_name_plural = 'Etapas'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class EdicaoCampus(models.Model):
    edicao = models.ForeignKey(Edicao, on_delete=models.CASCADE, verbose_name='Edição')
    campus = models.ForeignKey(Campus, on_delete=models.CASCADE, verbose_name='Campus')

    class Meta:
        verbose_name = 'Campus da Edição'
        verbose_name_plural = 'Campi da Edição'

    def __str__(self):
        return f"{self.pk}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Categoria(Base):
    nome = models.CharField(max_length=100, unique=True)
    idade_minima = models.IntegerField('Idade Mínima', blank=True, null=True)
    idade_maxima = models.IntegerField('Idade Máxima', blank=True, null=True)

    class Meta:
        verbose_name = 'Categoria Etária'
        verbose_name_plural = 'Categorias Etárias'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class EdicaoCategoria(Base):
    edicao = models.ForeignKey(Edicao, on_delete=models.CASCADE, verbose_name='Edição')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoria')
    regras = models.TextField('Regras', blank=True)

    class Meta:
        unique_together = ['edicao', 'categoria']
        verbose_name = 'Categoria da Edição'
        verbose_name_plural = 'Categorias da Edição'

    def __str__(self):
        return f"{self.edicao} {self.categoria}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Modalidade(Base):
    nome = models.CharField(max_length=100)
    tipo = models.CharField(max_length=1, choices=[['I', 'Individual'], ['C', 'Coletivo']])

    class Meta:
        unique_together = ['nome', 'tipo']
        verbose_name = 'Modalidade'
        verbose_name_plural = 'Modalidades'

    def __str__(self):
        return f"{self.nome} {'Individual' if self.tipo == 'I' else 'Coletivo'}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class EdicaoModalidade(Base):
    edicao = models.ForeignKey(Edicao, on_delete=models.CASCADE, verbose_name='Edição')
    modalidade = models.ForeignKey(Modalidade, on_delete=models.CASCADE, verbose_name='Modalidade')
    genero = models.CharField('Gênero', max_length=1, choices=[['M', 'Masculino'], ['F', 'Femenino']])
    limite_participantes_modalidade = models.IntegerField('Limite de Participantes na Modalidade', blank=False, null=False)

    class Meta:
        unique_together = ['edicao', 'modalidade', 'genero']
        verbose_name = 'Modalidade da Edição'
        verbose_name_plural = 'Modalidades da Edição'

    def __str__(self):
        return f"{self.modalidade} {'Masculino' if self.genero == 'M' else 'Femenino'} - {self.edicao}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Prova(Base):
    nome = models.CharField(max_length=100, unique=True)
    modalidade = models.ForeignKey(Modalidade, on_delete=models.CASCADE, verbose_name='Modalidade')

    class Meta:
        verbose_name = 'Prova'
        verbose_name_plural = 'Provas'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class EdicaoModalidadeProva(Base):
    edicao_modalidade = models.ForeignKey(EdicaoModalidade, on_delete=models.CASCADE, verbose_name='Modalidade')
    prova = models.ForeignKey(Prova, on_delete=models.CASCADE, verbose_name='Prova')
    limite_equipe_campus = models.IntegerField('Limite de Equipe por Campus', blank=False, null=False)
    limite_participante_equipe = models.IntegerField('Limite de Participante por Equipe', blank=False, null=False)
    limite_participante_individual = models.IntegerField('Limite de Participante Individual', blank=False, null=False)

    class Meta:
        unique_together = ['edicao_modalidade', 'prova']
        verbose_name = 'Prova da Modalidade'
        verbose_name_plural = 'Provas da Modalidade'

    def __str__(self):
        return f"{self.prova} - {self.edicao_modalidade}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Atleta(Base):
    campus = models.ForeignKey(Campus, on_delete=models.CASCADE, verbose_name='Campus')
    nome = models.CharField(max_length=100)
    foto = StdImageField(upload_to='atletas', variations={'thumb': (124, 124)},
                         blank=True)  # TODO Aperfeiçoar parâmetros: https://pypi.org/project/django-stdimage/
    cpf = models.CharField('CPF', max_length=11, unique=True)
    rg = models.CharField('RG', max_length=50, unique=True)
    matricula = models.CharField('Matrícula', max_length=20, unique=True)
    genero = models.CharField('Gênero', max_length=1, choices=[['M', 'Masculino'], ['F', 'Femenino']])
    data_nascimento = models.DateField('Data de Nascimento', blank=False, null=False)
    tipo_sanguineo = models.CharField('Tipo Sanguíneo', max_length=3, blank=True)
    plano_saude = models.CharField('Plano de Saúde', max_length=200, blank=True)
    numero_carteira_sus = models.CharField('Nº Carteira do SUS', max_length=20, blank=True)
    medicamento_controlado = models.TextField('Medicamento Controlado', blank=True)
    alergia = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Atleta'
        verbose_name_plural = 'Atletas'

    def __str__(self):
        return self.nome

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural


class Inscricao(Base):
    atleta = models.ForeignKey(Atleta, on_delete=models.CASCADE, verbose_name='Atleta')
    campus = models.ForeignKey(Campus, on_delete=models.CASCADE, verbose_name='Campus')
    etapa = models.ForeignKey(Etapa, on_delete=models.CASCADE, verbose_name='Etapa')
    edicao_prova = models.ForeignKey(EdicaoModalidadeProva, on_delete=models.CASCADE, verbose_name='Prova')

    objects = models.Manager()

    class Meta:
        unique_together = ['atleta', 'etapa', 'edicao_prova']
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'

    def __str__(self):
        return f"{self.pk}"

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural

jif/views/index_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from jif.models import Modalidade, Atleta, Inscricao


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login/'
    template_name = 'jif/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["qtd_modalidades"] = Modalidade.objects.count()
        context["qtd_atletas"] = Atleta.objects.count()
        context["qtd_inscricoes"] = Inscricao.objects.count()

        return context

jif/views/usuario_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class UsuarioView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login/'
    template_name = 'jif/usuario/detail.html'

jif/templates/jif/instituto/confirm_delete.html
{% extends 'base.html' %}

{% block nav_sidebar %}
	{% include 'jif/menu.html' %}
{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Início</a></li>
        <li class="breadcrumb-item">Cadastros</li>
        <li class="breadcrumb-item"><a href="{% url 'instituto' %}">{{instituto.get_verbose_name_plural}}</a></li>
        <li class="breadcrumb-item active">Excluir</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header">
            Excluir {{instituto.get_verbose_name}}
        </div>
         <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Você tem certeza que deseja excluir '{{ instituto.nome }}' ?</p>
                <div class="box-tools pull-left">
                    <input type="submit" class="btn btn-danger btn-sm" value="Excluir">
                    <a href="{% url 'instituto' %}" class="btn btn-primary btn-sm">Cancelar</a>
                </div>
            </form>
         </div>
    </div>
{% endblock %}

jif/templates/jif/instituto/detail.html
{% extends 'base.html' %}

{% block nav_sidebar %}
	{% include 'jif/menu.html' %}
{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Início</a></li>
        <li class="breadcrumb-item">Cadastros</li>
        <li class="breadcrumb-item"><a href="{% url 'instituto' %}">{{instituto.get_verbose_name_plural}}</a></li>
        <li class="breadcrumb-item active">Visualizar</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header">
            Visualizar {{instituto.get_verbose_name}}
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width:80px">
                            <span>Nome:</span>
                        </th>
                        <td>
                            <span>{{instituto.nome}}</span>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span>Sigla:</span>
                        </th>
                        <td>
                            <span>{{instituto.sigla}}</span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="text-center">
                <table class="table table-bordered mt-3">
                    <thead>
                        <tr>
                            <th>
                                <span>Data do Cadastro</span>
                            </th>
                            <th>
                                <span>Data da Última Alteração</span>
                            </th>
                            <th>
                                <span>Ativo</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <span>{{instituto.data_hora_cadastro}}</span>
                            </td>
                            <td>
                                <span>{{instituto.data_hora_ultima_alteracao}}</span>
                            </td>
                            <td>
                                {% if instituto.ativo %}
                                <i class="fa fa-check text-success" title="Sim"></i>
                                {% else %}
                                <i class="fa fa fa-remove text-danger" title="Não"></i>
                                {% endif %}
                            </td>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="box-tools pull-left">
                <a href="{% url 'instituto' %}" class="btn btn-primary btn-sm"> Voltar </a>
            </div>
        </div>
    </div>
{% endblock %}

jif/templates/jif/instituto/form.html
{% extends 'base.html' %}

{% block nav_sidebar %}
	{% include 'jif/menu.html' %}
{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Início</a></li>
        <li class="breadcrumb-item">Cadastros</li>
        <li class="breadcrumb-item"><a href="{% url 'instituto' %}">Institutos</a></li>
        {% if instituto %}
        <li class="breadcrumb-item active">Editar</li>
        {% else %}
        <li class="breadcrumb-item active">Adicionar</li>
        {% endif %}
    </ol>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header">
            {% if instituto %}
            Editar {{instituto.get_verbose_name}}
            {% else %}
            Adicionar Unidade Organizacional
            {% endif %}
        </div>
        <div class="card-body">
            <form method="post">
                {% if instituto %}
                <p>Você está editando '{{ instituto.nome }}' </p>
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <div class="box-tools pull-left">
                    <input type="submit" class="btn btn-primary btn-sm" value="Salvar">
                    <a href="{% url 'instituto' %}" class="btn btn-primary btn-sm">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

jif/templates/jif/instituto/list.html
{% extends 'base.html' %}

{% block nav_sidebar %}
    {% include 'jif/menu.html' %}
{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Início</a></li>
        <li class="breadcrumb-item">Cadastros</li>
        <li class="breadcrumb-item active">{{instituto.get_verbose_name_plural}}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header">
            {{instituto.get_verbose_name_plural}}
            <div class="box-tools pull-right">
                {% if perms.jif.add_instituto %}
                <a href="/instituto_create/" class="btn btn-primary btn-sm">
                    <i class="fa fa-plus"></i>
                    Adicionar {{instituto.get_verbose_name}}
                </a>
                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th></th>
                        <th>Nome</th>
                        <th>Sigla</th>
                        <th>Ativo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in institutos %}
                    <tr class="row1">
                        <td style="width:70px">
                            {% if perms.jif.view_instituto %}
                            <a href="/instituto/{{item.id}}" title="Visualizar"><i class="fa fa-eye text-info mr-1"></i></a>
                            {% endif %}
                            {% if perms.jif.change_instituto %}
                            <a href="/instituto/{{item.id}}/update" title="Editar"><i class="fa fa-edit text-warning mr-1"></i></a>
                            {% endif %}
                            {% if perms.jif.delete_instituto %}
                            <a href="/instituto/{{item.id}}/delete" title="Excluir" class="delete-btn"><i class="fa fa-trash text-danger"></i></a>
                            {% endif %}
                        </td>
                        <td>
                            <span>{{item.nome}}</span>
                        </td>
                        <td>
                            <span>{{item.sigla}}</span>
                        </td>
                        <td>
                            {% if item.ativo %}
                            <i class="fa fa-check text-success" title="Sim"></i>
                            {% else %}
                            <i class="fa fa fa-remove text-danger" title="Não"></i>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}